/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CmpImage */

#ifndef _Included_CmpImage
#define _Included_CmpImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CmpImage
 * Method:    expWithExp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_CmpImage_expWithExp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     CmpImage
 * Method:    expWithFolder
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
 /*
JNIEXPORT jstring JNICALL Java_CmpImage_expWithFolder
  (JNIEnv *, jobject, jstring, jstring);
*/
#ifdef __cplusplus
}
#endif
#endif
